# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-29 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20180528_0849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteOption',
        ),
        migrations.DeleteModel(
            name='SocialLink',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='image_name',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='title_other',
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='topiccontent',
            name='url',
        ),
        migrations.AlterField(
            model_name='topiccontent',
            name='video_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
