# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20181129_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccategory',
            name='title_other',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
