# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-03 07:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_topiccategory_title_other'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_s', models.CharField(max_length=100, null=True)),
                ('content_s', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='title_english',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='title_other',
            field=models.CharField(max_length=200),
        ),
    ]
